Found 3 servers:
	-3.88.227.75
	-3.88.58.239
	-3.80.42.49
Starting benchmark type aft with 5000 requests across 5 threads...
Number of errors: 0
Median latency: 0.045217
5th percentile/95th percentile: 0.038587, 0.063600
1st percentile/99th percentile: 0.036678, 0.094286
Total throughput: 105.001259

Starting benchmark type aft with 5000 requests across 5 threads...
Number of errors: 0
Median latency: 0.046084
5th percentile/95th percentile: 0.039553, 0.061996
1st percentile/99th percentile: 0.037737, 0.091482
Total throughput: 104.094185

Starting benchmark type aft with 5000 requests across 5 threads...
Errors: [{"errorMessage": "<_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses\"\n\tdebug_error_string = \"{\"created\":\"@1572312700.787483831\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3876,\"referenced_errors\":[{\"created\":\"@1572312700.787478717\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc\",\"file_line\":395,\"grpc_status\":14}]}\"\n>", "errorType": "_Rendezvous", "stackTrace": ["  File \"/var/task/distributed_handler.py\", line 53, in handler\n    client.Write(update)\n", "  File \"/var/task/grpc/_channel.py\", line 604, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n", "  File \"/var/task/grpc/_channel.py\", line 506, in _end_unary_response_blocking\n    raise _Rendezvous(state, None, None, deadline)\n"]}]
Number of errors: 1
Median latency: 0.045888
5th percentile/95th percentile: 0.039393, 0.061646
1st percentile/99th percentile: 0.037770, 0.091690
Total throughput: 98.139023

Finished!